# Configuração do Dependabot para fourmindsorg
# Mantém as dependências atualizadas automaticamente

version: 2
updates:
  # Dependências Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "fourmindsorg"
    assignees:
      - "fourmindsorg"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "fourmindsorg"
    assignees:
      - "fourmindsorg"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/aws-infrastructure"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "fourmindsorg"
    assignees:
      - "fourmindsorg"
    commit-message:
      prefix: "terraform"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"









