from authentication.models import PreferenciasUsuario

def tema_context(request):
    """Context processor para adicionar tema em todos os templates"""
    tema = 'default'
    modo = 'light'
    
    if request.user.is_authenticated:
        preferencias = PreferenciasUsuario.get_or_create_for_user(request.user)
        if preferencias:
            tema = preferencias.tema
            modo = preferencias.modo
    
    # Definir paletas de cores
    paletas_light = {
        'default': {
            'name': 'Azul Clássico',
            'primary': '#667eea',
            'secondary': '#764ba2',
            'success': '#28a745',
            'warning': '#ffc107',
            'danger': '#dc3545',
            'info': '#17a2b8',
            'light': '#f8f9fa',
            'dark': '#343a40',
            'background': '#ffffff',
            'surface': '#f8f9fa',
            'text': '#212529',
            'text_muted': '#6c757d',
            'border': '#dee2e6',
            'gradient': 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            'shadow': 'rgba(102, 126, 234, 0.4)',
        },
        'emerald': {
            'name': 'Verde Esmeralda',
            'primary': '#10b981',
            'secondary': '#059669',
            'success': '#22c55e',
            'warning': '#f59e0b',
            'danger': '#ef4444',
            'info': '#06b6d4',
            'light': '#f0fdf4',
            'dark': '#064e3b',
            'background': '#ffffff',
            'surface': '#f0fdf4',
            'text': '#212529',
            'text_muted': '#6c757d',
            'border': '#d1fae5',
            'gradient': 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
            'shadow': 'rgba(16, 185, 129, 0.4)',
        },
        'sunset': {
            'name': 'Pôr do Sol',
            'primary': '#f97316',
            'secondary': '#ea580c',
            'success': '#84cc16',
            'warning': '#eab308',
            'danger': '#dc2626',
            'info': '#0ea5e9',
            'light': '#fff7ed',
            'dark': '#9a3412',
            'background': '#ffffff',
            'surface': '#fff7ed',
            'text': '#212529',
            'text_muted': '#6c757d',
            'border': '#fed7aa',
            'gradient': 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
            'shadow': 'rgba(249, 115, 22, 0.4)',
        },
        'ocean': {
            'name': 'Oceano Profundo',
            'primary': '#0ea5e9',
            'secondary': '#0284c7',
            'success': '#059669',
            'warning': '#d97706',
            'danger': '#dc2626',
            'info': '#06b6d4',
            'light': '#f0f9ff',
            'dark': '#0c4a6e',
            'background': '#ffffff',
            'surface': '#f0f9ff',
            'text': '#212529',
            'text_muted': '#6c757d',
            'border': '#bae6fd',
            'gradient': 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
            'shadow': 'rgba(14, 165, 233, 0.4)',
        },
        'purple': {
            'name': 'Roxo Elegante',
            'primary': '#8b5cf6',
            'secondary': '#7c3aed',
            'success': '#10b981',
            'warning': '#f59e0b',
            'danger': '#ef4444',
            'info': '#06b6d4',
            'light': '#faf5ff',
            'dark': '#581c87',
            'background': '#ffffff',
            'surface': '#faf5ff',
            'text': '#212529',
            'text_muted': '#6c757d',
            'border': '#e9d5ff',
            'gradient': 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
            'shadow': 'rgba(139, 92, 246, 0.4)',
        }
    }
    
    # Paletas para modo escuro
    paletas_dark = {
        'default': {
            'name': 'Azul Clássico',
            'primary': '#818cf8',
            'secondary': '#a78bfa',
            'success': '#34d399',
            'warning': '#fbbf24',
            'danger': '#f87171',
            'info': '#22d3ee',
            'light': '#374151',
            'dark': '#f9fafb',
            'background': '#111827',
            'surface': '#1f2937',
            'text': '#f9fafb',
            'text_muted': '#9ca3af',
            'border': '#374151',
            'gradient': 'linear-gradient(135deg, #818cf8 0%, #a78bfa 100%)',
            'shadow': 'rgba(129, 140, 248, 0.4)',
        },
        'emerald': {
            'name': 'Verde Esmeralda',
            'primary': '#34d399',
            'secondary': '#10b981',
            'success': '#22c55e',
            'warning': '#fbbf24',
            'danger': '#f87171',
            'info': '#22d3ee',
            'light': '#064e3b',
            'dark': '#f0fdf4',
            'background': '#0f1419',
            'surface': '#1a2e05',
            'text': '#f0fdf4',
            'text_muted': '#86efac',
            'border': '#166534',
            'gradient': 'linear-gradient(135deg, #34d399 0%, #10b981 100%)',
            'shadow': 'rgba(52, 211, 153, 0.4)',
        },
        'sunset': {
            'name': 'Pôr do Sol',
            'primary': '#fb923c',
            'secondary': '#f97316',
            'success': '#a3e635',
            'warning': '#fbbf24',
            'danger': '#f87171',
            'info': '#38bdf8',
            'light': '#431407',
            'dark': '#fff7ed',
            'background': '#1c1917',
            'surface': '#292524',
            'text': '#fff7ed',
            'text_muted': '#fdba74',
            'border': '#78350f',
            'gradient': 'linear-gradient(135deg, #fb923c 0%, #f97316 100%)',
            'shadow': 'rgba(251, 146, 60, 0.4)',
        },
        'ocean': {
            'name': 'Oceano Profundo',
            'primary': '#38bdf8',
            'secondary': '#0ea5e9',
            'success': '#34d399',
            'warning': '#fbbf24',
            'danger': '#f87171',
            'info': '#22d3ee',
            'light': '#0c4a6e',
            'dark': '#f0f9ff',
            'background': '#0f172a',
            'surface': '#1e293b',
            'text': '#f0f9ff',
            'text_muted': '#7dd3fc',
            'border': '#1e40af',
            'gradient': 'linear-gradient(135deg, #38bdf8 0%, #0ea5e9 100%)',
            'shadow': 'rgba(56, 189, 248, 0.4)',
        },
        'purple': {
            'name': 'Roxo Elegante',
            'primary': '#a78bfa',
            'secondary': '#8b5cf6',
            'success': '#34d399',
            'warning': '#fbbf24',
            'danger': '#f87171',
            'info': '#22d3ee',
            'light': '#581c87',
            'dark': '#faf5ff',
            'background': '#1e1b4b',
            'surface': '#312e81',
            'text': '#faf5ff',
            'text_muted': '#c4b5fd',
            'border': '#6d28d9',
            'gradient': 'linear-gradient(135deg, #a78bfa 0%, #8b5cf6 100%)',
            'shadow': 'rgba(167, 139, 250, 0.4)',
        }
    }
    
    # Escolher paleta baseada no modo
    paletas = paletas_dark if modo == 'dark' else paletas_light
    
    return {
        'tema_atual': tema,
        'modo_atual': modo,
        'paleta_cores': paletas.get(tema, paletas['default']),
        'todas_paletas': paletas_light,  # Sempre mostrar paletas claras no seletor
        'is_dark_mode': modo == 'dark',
    }