# Generated by Django 4.2.25 on 2025-10-17 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_preferenciasusuario_modo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Plano')),
                ('tipo', models.CharField(choices=[('gratuito', 'Período Gratuito'), ('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, unique=True, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco_cartao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço no Cartão')),
                ('preco_pix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço no PIX')),
                ('duracao_dias', models.IntegerField(verbose_name='Duração em Dias')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Plano em Destaque')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada'), ('suspensa', 'Suspensa')], default='ativa', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Método de Pagamento')),
                ('asaas_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Pagamento Asaas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='authentication.plano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura do Usuário',
                'verbose_name_plural': 'Assinaturas dos Usuários',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
