# Generated by Django 4.2.25 on 2025-10-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_plano_assinaturausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturausuario',
            name='status',
            field=models.CharField(choices=[('aguardando_pagamento', 'Aguardando Pagamento'), ('ativa', 'Ativa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada'), ('suspensa', 'Suspensa')], default='aguardando_pagamento', max_length=20),
        ),
    ]
