# Generated by Django 4.2.25 on 2025-11-10 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_alter_assinaturausuario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.PositiveBigIntegerField(default=0)),
                ('total_get_requests', models.PositiveBigIntegerField(default=0)),
                ('total_post_requests', models.PositiveBigIntegerField(default=0)),
                ('total_put_requests', models.PositiveBigIntegerField(default=0)),
                ('total_delete_requests', models.PositiveBigIntegerField(default=0)),
                ('total_login_success', models.PositiveIntegerField(default=0)),
                ('total_login_failed', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('last_request_path', models.CharField(blank=True, max_length=512)),
                ('last_user_agent', models.CharField(blank=True, max_length=512)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('estimated_data_volume_bytes', models.BigIntegerField(default=0)),
                ('last_data_volume_calculated', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Atividade do Usuário',
                'verbose_name_plural': 'Registros de Atividades dos Usuários',
            },
        ),
    ]
