# Generated by Django 4.2.25 on 2025-11-10 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_populate_user_activity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('document_type', models.CharField(choices=[('terms_of_use', 'Termos de Uso'), ('privacy_policy', 'Política de Privacidade'), ('service_contract', 'Contrato de Prestação de Serviços'), ('other', 'Outro')], default='other', max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_explicit_acceptance', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legais',
                'ordering': ['document_type', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('record_source', models.CharField(blank=True, help_text='Origem do aceite (ex: cadastro web).', max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='authentication.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceite de Documento Legal',
                'verbose_name_plural': 'Aceites de Documentos Legais',
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'document', 'version')},
            },
        ),
    ]
