# Generated by Django 4.2.25 on 2025-11-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_legaldocument_userlegalacceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms_of_use', 'Termos de Uso'), ('privacy_policy', 'Política de Privacidade'), ('service_contract', 'Contrato de Adesão')], default='terms_of_use', max_length=40),
        ),
    ]
