# Generated by Django 4.2.25 on 2025-10-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_id', models.CharField(max_length=64, unique=True)),
                ('customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('copy_paste_payload', models.TextField(blank=True, null=True)),
                ('invoice_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_event_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
